services:
  db:
    image: postgres:16-alpine
    container_name: openbao-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  openbao:
    build: .
    container_name: openbao-server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8200:8200"
    volumes:
      - ./data:/bao/data # keys.json backup
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
